---
- name: Create a login user
  user:
    name: {{ item.username }}
    password: '???'
    groups: # Empty by default, here we give it some groups
      - docker
      - sudo
    state: present
    shell: /bin/bash                 # Defaults to /bin/bash
    system: no                       # Defaults to no
    createhome: yes                  # Defaults to yes
    home: /home/{{ item.username }}  # Defaults to /home/<username>
  with_items:
    - { username: 'finch348'  }