# only common items
---

- name: Launching tasks to install standard system packages.
  import_tasks: common-packages.yaml
  when: install_os_packages

- name: Launching tasks to enable NTP.
  import_tasks: ntp.yaml
  when: configure_ntp

- name: Launching tasks update CA Trust.
  import_tasks: ca-trust.yaml
  when: configure_ca_trust

# - name: Add motd
#   template: src=motd.j2 dest=/etc/motd
#   tags: motd
#   when: configure_motd
