---
- name: User Sync
  user:
    name: {{ item.username }}
    password: {{ item.password }}
    groups: {{ item.groups }}
    state: {{ item.state }}
    shell: {{ item.shell }} # Defaults to /bin/bash
    remove: no # only lock when deactivating
    system: no # Defaults to no
    createhome: yes # Defaults to yes
    home: /home/{{ item.username }} # Defaults to /home/<username>
  with_items: {{ linux_users }}